<%@ Page Title="Customer Order" Language="vb" AutoEventWireup="false" MasterPageFile="~/Site.Master" CodeBehind="Customer_Order.aspx.vb" Inherits="VBPOAssignment.Customer_Order" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">

    <form runat="server">
            <br />
        <h2>View Orders</h2>
        <p>Click Order Number to edit Order</p>
    <br />
        <asp:GridView ID="ordGridView" runat="server" AutoGeneratedColumns="False" DataKeyNames="orderId" ShowHeaderWhenEmpty="True" AutoGenerateColumns="False" >
      <Columns>
           <asp:ButtonField DataTextField="orderId" HeaderText="Order ID" CommandName="OrderSelected_click"  />
           <asp:BoundField DataField="orderDate" HeaderText="Order Date" />
           <asp:BoundField DataField="cust" HeaderText="Customer Id" />
          <asp:CommandField ShowDeleteButton="true"  />
       </Columns>
        </asp:GridView>

        <br /><br />
        <asp:GridView ID="prodGridView" runat="server" AutoGeneratedColumns="False" DataKeyNames="productId" ShowHeaderWhenEmpty="True" AutoGenerateColumns="False" >
      <Columns>
           <asp:BoundField DataField="productId" HeaderText="Product ID" ReadOnly="true" />
           <asp:BoundField DataField="description" HeaderText="Description" ReadOnly="true" />
           <asp:BoundField DataField="price" HeaderText="Price" ReadOnly="true" />
           <asp:BoundField DataField="quantityOrdered" HeaderText="Quantity Ordered" />
          <asp:CommandField ShowDeleteButton="true" ShowEditButton="true" />
       </Columns>

        </asp:GridView>
    <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <asp:Label ID="Label1" runat="server" Text=""></asp:Label>

    <br />
    <br />
    <br />
    </form>
</asp:Content>
