<%@ Page Title="" Language="vb" AutoEventWireup="false" MasterPageFile="~/Site1.Master" CodeBehind="Orders.aspx.vb" Inherits="VBPOAssignment.Orders" %>
<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
<form runat="server">
     <br /><br />
        <asp:GridView ID="ordGridView" runat="server" AutoGeneratedColumns="False" DataKeyNames="orderId" ShowHeaderWhenEmpty="True" AutoGenerateColumns="False" >
      <Columns>
           <asp:boundfield Datafield="orderId" HeaderText="Order ID"  />
           <asp:BoundField DataField="orderDate" HeaderText="Order Date" />
           <asp:BoundField DataField="cust" HeaderText="Customer Id" />
          <asp:CommandField ShowDeleteButton="true"  />
       </Columns>
        </asp:GridView>

        <br /><br />
   
    <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <asp:Label ID="Label1" runat="server" Text=""></asp:Label>

    <br />
    <br />
    <br />
</form>
    </asp:Content>

