<%@ Page Language="vb" Title="Products" MasterPageFile="~/Site1.Master" AutoEventWireup="false" CodeBehind="Product.aspx.vb" Inherits="VBPOAssignment.Product1" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <form runat="server">
        &nbsp;&nbsp;
    <br />
    <asp:Button ID="addProdButton" runat="server" Text="Add New Product" PostBackUrl="~/AddProduct.aspx"  />
    <br />
    <br />
        <asp:GridView ID="prodGridView" runat="server" AutoGeneratedColumns="False" DataKeyNames="productId" ShowHeaderWhenEmpty="True" AutoGenerateColumns="False" >
      <Columns>
           <asp:BoundField DataField="productId" HeaderText="Product ID" ReadOnly="true" />
           <asp:BoundField DataField="description" HeaderText="Description" />
           <asp:BoundField DataField="price" HeaderText="Price" />
           <asp:BoundField DataField="quantity" HeaderText="Quantity" />
           <asp:BoundField DataField="reorderNumber" HeaderText="ReOrder Number" />
          <asp:CommandField ShowDeleteButton="true" ShowEditButton="true" />
       </Columns>
        </asp:GridView>
</form>
    </asp:Content>
