<%@ Page Title="Puchase Order" Language="vb" AutoEventWireup="false" MasterPageFile="~/Site.Master" CodeBehind="Purchase_Order.aspx.vb" Inherits="VBPOAssignment.Purchase_Order" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <form runat="server">
        <h1>New Order</h1>
       <div>
            <br />
            Order Date :&nbsp;&nbsp;&nbsp;
            <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
            <br />
            <br />
            Select the Products and the quatity to order<br />
            <br />
            <asp:GridView ID="prodGridView" runat="server" AutoGenerateColumns="False" AutoGeneratedColumns="False" DataKeyNames="productId" ShowHeaderWhenEmpty="True">
                <Columns>
                    <asp:BoundField DataField="productId" HeaderText="Product ID" ReadOnly="true" />
                    <asp:BoundField DataField="description" HeaderText="Description" />
                    <asp:BoundField DataField="price" HeaderText="Price" />
                    <asp:BoundField DataField="quantity" HeaderText="Quantity" />
                    <asp:BoundField DataField="quantityOrdered" HeaderText="Order Quantity" nulldisplayText="0" />
                     <asp:TemplateField>
                    
                    <ItemTemplate>
                         <asp:Label ID="Label3" runat="server" AssociatedControlID="OrderQuantity"><HeaderTemplate>Enter Order Quantity </HeaderTemplate></asp:Label>
        <asp:TextBox ID="OrderQuantity" enabled=false runat="server" class="form-control"></asp:TextBox>
        <asp:RangeValidator id="Range1" CssClass="rfv"
           ControlToValidate=OrderQuantity MinimumValue="0" MaximumValue="100"
           Type="Integer" errormessage="Quantity must be from 0 to 100!" runat="server"/>


                     </ItemTemplate>
                    </asp:TemplateField>


                    <asp:TemplateField HeaderStyle-HorizontalAlign="Center" HeaderStyle-CssClass="title_bg" ItemStyle-HorizontalAlign="Center">
                     <HeaderTemplate>
                        Select
                    </HeaderTemplate>
                     <ItemTemplate>
                            <asp:CheckBox runat="server"  ID="ProductSelected" OnCheckedChanged="ProductSelected_CheckedChanged" Checked="false"  AutoPostBack="True"/>
                     </ItemTemplate>

                        <HeaderStyle HorizontalAlign="Center" CssClass="title_bg"></HeaderStyle>

                 <ItemStyle HorizontalAlign="Center"></ItemStyle>
                    </asp:TemplateField>        
                </Columns>
            </asp:GridView>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; Total Cost :&nbsp;&nbsp;
            <asp:Label ID="Label1" runat="server" Text=""></asp:Label>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;
            <asp:Button ID="Button1" runat="server" Text="Order" Width="135px" />
            <br />
            <br />
            <asp:Label ID="Label2" runat="server" Text=""></asp:Label>
            <br />
            <br />
            <asp:Label ID="Label3" runat="server" Text=""></asp:Label>
            <br />
        </div>
    </form>
</asp:Content>
